 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "hostname"
             hostname
       - run:
            name: Deploy Over SSH2
            command: |
             ssh $SSH_USER@$SSH_HOST_PRIVATE "touch text.text"
             hostname
             touch text.text
 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: main # only deploy on the main branch
