 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     working_directory: ~/
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST
             hostname
             SSH_USER@$SSH_HOST_PRIVATE
             hostname
             exit
             exit
       - run:
            name: Deploy Over SSH2
            command: |
             ssh $SSH_USER@$SSH_HOST "hostname"
             ssh $SSH_USER@$SSH_HOST "$SSH_USER@$SSH_HOST_PRIVATE "hostname""
 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: main # only deploy on the main branch
