 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - checkout
       - run:
           name: Deploy Over SSH
           command: |
             ls
             mkdir hello
             scp -r ~/hello SSH_USER@$SSH_HOST:/home/ubuntu 
             ssh $SSH_USER@$SSH_HOST
             hostname
       - run:
            name: Deploy Over SSH2
            command: |
             ssh $SSH_USER@$SSH_HOST_PRIVATE
             hostname
             touch text.text
 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: main # only deploy on the main branch
