 version: 2
 jobs:
   deploy:
     machine:
       enabled: true
     working_directory: ~/f
     steps:
       - checkout
       - run: pwd
       - run: ls #
       - run: scp -r ./ansible "$SSH_USER@$SSH_HOST:/home/$SSH_USER" # for ansible from checkout
       - run: ssh $SSH_USER@$SSH_HOST "hostname"
       - run: ssh $SSH_USER@$SSH_HOST "ansible dev -i /home/ubuntu/ansible/inventory -m file -a 'path=/home/ubuntu_test.txt state=touch'"

 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: main # only deploy on the main branch
# ssh $SSH_USER@$SSH_HOST "ansible dev -m command -a 'hostname'"
# - run: ssh $SSH_USER@$SSH_HOST "ansible-playbook /home/ubuntu/ansible/playbook.yaml"